"""add_description_to_criteria

Revision ID: 08bc97f87999
Revises: 07e76aaeb669
Create Date: 2026-05-18 18:42:06.516750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '08bc97f87999'
down_revision: Union[str, Sequence[str], None] = '07e76aaeb669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterias', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterias', 'description')
    # ### end Alembic commands ###
