"""new_table_comment_pattern_and_change_invite_link

Revision ID: 3a95c306f8b7
Revises: 08bc97f87999
Create Date: 2026-06-06 16:16:21.914463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a95c306f8b7'
down_revision: Union[str, Sequence[str], None] = '08bc97f87999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_patterns',
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_patterns_user_id'), 'comment_patterns', ['user_id'], unique=False)
    op.add_column('groups', sa.Column('invite_token', sa.String(length=36), nullable=False))
    op.drop_constraint('groups_invite_code_key', 'groups', type_='unique')
    op.create_unique_constraint(None, 'groups', ['invite_token'])
    op.drop_column('groups', 'invite_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('invite_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='unique')
    op.create_unique_constraint('groups_invite_code_key', 'groups', ['invite_code'])
    op.drop_column('groups', 'invite_token')
    op.drop_index(op.f('ix_comment_patterns_user_id'), table_name='comment_patterns')
    op.drop_table('comment_patterns')
    # ### end Alembic commands ###
