"""Create initial tables

Revision ID: be0d1d75907b
Revises: 
Create Date: 2026-05-18 09:43:18.963211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0d1d75907b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('invite_code', sa.String(length=6), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refresh_token',
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('is_p2p_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_group_id'), 'tasks', ['group_id'], unique=False)
    op.create_table('users_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_status', sa.Enum('EXPERT', 'STUDENT', name='userstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='unique_group_user_id')
    )
    op.create_index(op.f('ix_users_groups_group_id'), 'users_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_users_groups_user_id'), 'users_groups', ['user_id'], unique=False)
    op.create_table('criterias',
    sa.Column('criteria_name', sa.String(length=100), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criterias_task_id'), 'criterias', ['task_id'], unique=False)
    op.create_table('solutions',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_PASSED', 'IN_PROGRESS', 'CHECKED', name='solutionstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_student_id'), 'solutions', ['student_id'], unique=False)
    op.create_index(op.f('ix_solutions_task_id'), 'solutions', ['task_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('overall_comment', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('commented_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_reviewer_id'), 'feedbacks', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_solution_id'), 'feedbacks', ['solution_id'], unique=False)
    op.create_table('feedbacks_for_criteria',
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['criterias.id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id', 'criteria_id', name='unique_criteria_id')
    )
    op.create_index(op.f('ix_feedbacks_for_criteria_criteria_id'), 'feedbacks_for_criteria', ['criteria_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_for_criteria_feedback_id'), 'feedbacks_for_criteria', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_for_criteria_feedback_id'), table_name='feedbacks_for_criteria')
    op.drop_index(op.f('ix_feedbacks_for_criteria_criteria_id'), table_name='feedbacks_for_criteria')
    op.drop_table('feedbacks_for_criteria')
    op.drop_index(op.f('ix_feedbacks_solution_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_reviewer_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_solutions_task_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_student_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_criterias_task_id'), table_name='criterias')
    op.drop_table('criterias')
    op.drop_index(op.f('ix_users_groups_user_id'), table_name='users_groups')
    op.drop_index(op.f('ix_users_groups_group_id'), table_name='users_groups')
    op.drop_table('users_groups')
    op.drop_index(op.f('ix_tasks_group_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
