"""add reviewer_id to solution for p2p

Revision ID: c7c591be3cd7
Revises: 3a95c306f8b7
Create Date: 2026-06-10 17:04:46.121827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c591be3cd7'
down_revision: Union[str, Sequence[str], None] = '3a95c306f8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_solutions_reviewer_id'), 'solutions', ['reviewer_id'], unique=False)
    op.create_foreign_key(None, 'solutions', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solutions', type_='foreignkey')
    op.drop_index(op.f('ix_solutions_reviewer_id'), table_name='solutions')
    op.drop_column('solutions', 'reviewer_id')
    # ### end Alembic commands ###
