"""New table comment_pattern and change group to invait_link

Revision ID: c8ef0a3eacf9
Revises: 08bc97f87999
Create Date: 2026-06-05 18:33:07.934597

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8ef0a3eacf9'
down_revision: Union[str, Sequence[str], None] = '08bc97f87999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_patterns',
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_patterns_user_id'), 'comment_patterns', ['user_id'], unique=False)
    op.drop_index('ix_verification_codes_email', table_name='verification_codes')
    op.drop_table('verification_codes')

    # Step 1: Add invite_token as nullable first
    op.add_column('groups', sa.Column('invite_token', sa.String(length=36), nullable=True))

    # Step 2: Fill existing rows with unique UUIDs
    # Get the table name and generate UUIDs for all existing rows
    groups_table = sa.table(
        'groups',
        sa.column('id', sa.Integer),
        sa.column('invite_token', sa.String(36)),
    )
    conn = op.get_bind()
    result = conn.execute(sa.select(groups_table.c.id).order_by(groups_table.c.id))
    for row in result:
        conn.execute(
            sa.update(groups_table)
            .where(groups_table.c.id == row[0])
            .values(invite_token=str(uuid4()))
        )

    # Step 3: Now make it NOT NULL and add unique constraint
    op.alter_column('groups', 'invite_token', nullable=False)
    op.drop_constraint('groups_invite_code_key', 'groups', type_='unique')
    op.create_unique_constraint(None, 'groups', ['invite_token'])
    op.drop_column('groups', 'invite_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('invite_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='unique')
    op.create_unique_constraint('groups_invite_code_key', 'groups', ['invite_code'])
    op.drop_column('groups', 'invite_token')
    op.create_table('verification_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='verification_codes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='verification_codes_pkey')
    )
    op.create_index('ix_verification_codes_email', 'verification_codes', ['email'], unique=False)
    op.drop_index(op.f('ix_comment_patterns_user_id'), table_name='comment_patterns')
    op.drop_table('comment_patterns')
    # ### end Alembic commands ###
